spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: jheanrabelo
    password: 'MinhaSenhaSegura123!'
    driver-class-name: com.mysql.cj.jdbc.Driver